### ISSUE TITLE
How to shorten the content of notification?

### ISSUE THREAD

**Issue by khoi-thinh** [hokkey/redmine_chatwork#6]
Hi,
I installed your plugin and it worked perfectly.
There's one thing: I'd like to keep the notification in ChatWork to be short.
For example, i want to remove the "By: Redmine Admin, Assignee: Redmine Admin, Author: Redmine Admin" part.
Is that possible?

**Comment by hokkey** [comment]
@khoi-thinh: 
I agree those labels are redundant and I have understood too long messages appear if we send multiple notifications. But **I think those labels are also needed to know the ticket state without reading the recent context**. So I don't agree to remove them. I can add plugin options to control which labels to show in posts, but that is not simple. I don't want to add unnecessary detailed options.

Instead of that, I'm considering to move user labels to the outside of a header to also fix #5:
![image](https://user-images.githubusercontent.com/6197292/33643809-ae74b0e8-da84-11e7-9124-2b95bc36161f.png)

**Comment by khoi-thinh** [comment]
Thank you.
I edited your code in my Linux environment and it worked now.

**Comment by hokkey** [comment]
I got it. You can modify the header template for your environment. Thanks!
https://github.com/hokkey/redmine_chatwork/blob/ea9941753ead2d3b48ad1b98ffb92abf94bb21b3/src/redmine_chatwork/lib/redmine_chatwork/listener.rb#L101
